### ISSUE TITLE
U-boot 2019.* support for ast2500

### ISSUE THREAD

**Issue by ytmhub** [openbmc/u-boot#23]
Does this version also work on ast2500?

The main reason it would be useful (for me, at least), would be i2c support (for eeprom), and dts (for fixups).

**Comment by ytmhub** [comment]
For anyone interested, I eventually managed to boot without issues, by changing the watchdog configuration in reset-controller node in ast2500-u-boot.dtsi, from:
aspeed,wdt = <&wdt1>;
to:
aspeed,wdt = <&wdt2>;

Without it, sticking around for 22 seconds would result in u-boot reset, since the wrong watchdog is stopped on the watchdog driver probe function.

Configuring u-boot environment size and offset (CONFIG_ENV_SIZE/OFFSET) to sizes that accommodate the now larger u-boot image was also required, in order to be able to correctly find and load the fit image.

It should also be noted that the Yocto layer and kernel dts partitions also need to be updated in order to support the larger u-boot image.

**Comment by godunkchen** [comment]
Hi @ytmhub,

Wondering if your mentioning below is also applying to my current observation of error 'u-boot.bin too large' while building u-boot image in Yocto environment.

> 'It should also be noted that the Yocto layer and kernel dts partitions also need to be updated in order to support the larger u-boot image.'


I've tried to build openbmc on ast2600 evb with a simple *clone* from ast2500 evb
- do a copy from 'meta-evb/meta-evb-aspeed/meta-evb-ast2500' to 'meta-evb/meta-evb-aspeed/meta-evb-ast2600' with necessary change (2500 -> 2600)
- TEMPLATECONF=meta-evb/meta-evb-aspeed/meta-evb-ast2600/conf . openbmc-env
- bitbake obmc-phosphor-image

Then following error occurred:
May I have your comment on the possible fix and did you also see this same issue on ast2500 evb?

> Build Configuration:
BB_VERSION           = "1.47.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "arm-openbmc-linux-gnueabi"
MACHINE              = "evb-ast2600"
DISTRO               = "openbmc-phosphor"
DISTRO_VERSION       = "0.1.0"
TUNE_FEATURES        = "arm armv7a vfp vfpv4d16 callconvention-hard"
TARGET_FPU           = "hard"
meta
meta-poky
meta-oe
meta-networking
meta-python
meta-webserver
meta-phosphor
meta-aspeed
meta-evb
meta-evb-aspeed
meta-evb-ast2600     = "master:6e220b3d1bdd75972a28a4f4cb11d3c00b9def91"

>Initialising tasks: 100% |################################################################################################################################| Time: 0:00:03
Sstate summary: Wanted 1 Found 0 Missed 1 Current 1329 (0% match, 99% complete)
NOTE: Executing Tasks
ERROR: obmc-phosphor-image-1.0-r0 do_generate_static: Image '/home/ladmin/Projects/openbmc/openbmc.git/build/tmp/deploy/images/evb-ast2600/u-boot.bin' is too large!
ERROR: Logfile of failure stored in: /home/ladmin/Projects/openbmc/openbmc.git/build/tmp/work/evb_ast2600-openbmc-linux-gnueabi/obmc-phosphor-image/1.0-r0/temp/log.do_generate_static.32505
ERROR: Task (/home/ladmin/Projects/openbmc/openbmc.git/meta-phosphor/recipes-phosphor/images/obmc-phosphor-image.bb:do_generate_static) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3905 tasks of which 3904 didn't need to be rerun and 1 failed.

>Summary: 1 task failed:
  /home/ladmin/Projects/openbmc/openbmc.git/meta-phosphor/recipes-phosphor/images/obmc-phosphor-image.bb:do_generate_static
Summary: There were 9 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by ytmhub** [comment]
Yeah, I had the same issue, I needed to change FLASH_KERNEL_OFFSET value from 512 to 1024 in the machine config file I'm using in my layer, in order to allow more room for u-boot.
After you do that, make sure that you align this in the flash partitions definition in your dts.

**Comment by godunkchen** [comment]
Thanks, @ytmhub.

**Comment by mdmillerii** [comment]
You probably need to fix the env location in both `u-boot` and maybe the `fw_setenv` recipes if the binary grew. (Thinking about it the fw-env uses the partitions in the dts).
