### ISSUE TITLE
How to update the second bmc flash through u-boot

### ISSUE THREAD

**Issue by justin0309** [openbmc/u-boot#31]
Our bmc chip is ast-2500

I have used devtool modify u-boot-aspeed package. The current question is how do I confirm my u-boot dts?
Currently, bmc firmware update through u-boot can only update the first flash but cannot update the second one.On our kernel dts, I have added the partition of flash1 and updated it through scp to confirm that the two flash and image can be recognized.

How should I add the second flash to u-boot dts?
Thanks.

**Comment by mdmillerii** [comment]
I am not aware of anyone having enabled the second flash in u-boot although upstream does support the concept.

The only way to boot u-boot of the second flash device (without hardware support to change the cs routing - eg via jumpers) is to program a watchdog timer to expire with the toggle select mode.   

Some systems have used devmem in u-boot to setup the watchdog to a short remaining timeout albeit a longer interval to achieve this.

As far as programming the flash, the convention is to use the same partition names but prefixed with alt as the kernel doesn't know which device it's redirected to select.

The 2400 and earlier or the select but as I remember the 2500 and later xor or swap the select number.

As this is a question and not a bug report the community asks for discussion in discord or the mailing list.

**Comment by justin0309** [comment]
@mdmillerii 
Ok thanks. I will close this issue.
