### ISSUE TITLE
Need non-nsci config for Firestone.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/u-boot#9]

**Comment by adamliyi** [comment]
Hi @shenki , please let me know when firestone u-boot configure is ready. I can update the firestone openbmc yocto configure. -thanks.

**Comment by adamliyi** [comment]
@shenki, I think this issue has been fixed by your commit: https://github.com/openbmc/u-boot/commit/f9b2a49f57c153c7358f9769234c0cefdf4de8d4 , is that right?

**Comment by shenki** [comment]
Yes. This is resolved for u-boot.
